from models.exercicios import Exercicio
from models.enums import GrupoMuscularEnum

def obter_catalogo_inicial():
    return [

    Exercicio(nome="Supino reto na máquina", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=1),
    Exercicio(nome="Peck Deck (Voador)", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=1),
    Exercicio(nome="Crossover no cabo", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=1),
    Exercicio(nome="Chest Press sentado", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=1),
    Exercicio(nome="Supino reto com halteres", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=2),
    Exercicio(nome="Supino reto com barra", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=2),
    Exercicio(nome="Supino inclinado com halteres", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=2),
    Exercicio(nome="Supino inclinado com barra", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=2),
    Exercicio(nome="Supino declinado", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=2),
    Exercicio(nome="Crucifixo com halteres", grupoMuscular=GrupoMuscularEnum.PEITO, impacto_articular=3),

    Exercicio(nome="Puxada frontal", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=1),
    Exercicio(nome="Puxada neutra", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=1),
    Exercicio(nome="Remada baixa no cabo", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=1),
    Exercicio(nome="Remada articulada na máquina", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=1),
    Exercicio(nome="Pullover na máquina", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=1),
    Exercicio(nome="Remada unilateral com halter", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=2),
    Exercicio(nome="Remada curvada com barra", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=3),
    Exercicio(nome="Remada cavalinho (T-Bar)", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=3),
    Exercicio(nome="Levantamento terra", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=3),
    Exercicio(nome="Rack Pull", grupoMuscular=GrupoMuscularEnum.COSTAS, impacto_articular=3),

    Exercicio(nome="Cadeira extensora", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=1),
    Exercicio(nome="Leg Press 45°", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=1),
    Exercicio(nome="Hack Machine", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=1),
    Exercicio(nome="Smith Machine Squat", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=2),
    Exercicio(nome="Goblet Squat", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=2),
    Exercicio(nome="Agachamento livre", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=3),
    Exercicio(nome="Agachamento frontal", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=3),
    Exercicio(nome="Afundo com halteres", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=3),
    Exercicio(nome="Passada com halteres", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=3),
    Exercicio(nome="Agachamento búlgaro", grupoMuscular=GrupoMuscularEnum.QUADRICEPS, impacto_articular=3),

    Exercicio(nome="Mesa flexora", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=1),
    Exercicio(nome="Cadeira flexora", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=1),
    Exercicio(nome="Flexora em pé", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=1),
    Exercicio(nome="Romanian Deadlift com halteres", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=2),
    Exercicio(nome="Romanian Deadlift com barra", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=2),
    Exercicio(nome="Stiff com halteres", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=2),
    Exercicio(nome="Stiff com barra", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=3),
    Exercicio(nome="Good Morning", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=3),
    Exercicio(nome="Deadlift convencional", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=3),
    Exercicio(nome="Deadlift sumô", grupoMuscular=GrupoMuscularEnum.POSTERIOR_COXA, impacto_articular=3),

    Exercicio(nome="Abdução na máquina", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=1),
    Exercicio(nome="Glute Drive", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=1),
    Exercicio(nome="Coice no cabo", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=1),
    Exercicio(nome="Hip Thrust na máquina", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=1),
    Exercicio(nome="Hip Thrust com barra", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=2),
    Exercicio(nome="Cable Pull Through", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=2),
    Exercicio(nome="Step-up com halteres", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=2),
    Exercicio(nome="Agachamento sumô com halter", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=2),
    Exercicio(nome="Afundo com halteres", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=3),
    Exercicio(nome="Agachamento búlgaro", grupoMuscular=GrupoMuscularEnum.GLUTEOS, impacto_articular=3),

    Exercicio(nome="Panturrilha sentada", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=1),
    Exercicio(nome="Panturrilha no Leg Press", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=1),
    Exercicio(nome="Panturrilha na máquina", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=1),
    Exercicio(nome="Panturrilha no Smith", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=2),
    Exercicio(nome="Panturrilha em pé na máquina", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=2),
    Exercicio(nome="Panturrilha unilateral com halter", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=2),
    Exercicio(nome="Donkey Calf Raise", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=2),
    Exercicio(nome="Farmer Walk na ponta dos pés", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=3),
    Exercicio(nome="Panturrilha em pé com barra", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=3),
    Exercicio(nome="Panturrilha unilateral no Smith", grupoMuscular=GrupoMuscularEnum.PANTURRILHA, impacto_articular=3),

    Exercicio(nome="Desenvolvimento na máquina", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=1),
    Exercicio(nome="Elevação lateral na máquina", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=1),
    Exercicio(nome="Face Pull", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=1),
    Exercicio(nome="Elevação lateral no cabo", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=1),
    Exercicio(nome="Crucifixo inverso na máquina", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=1),
    Exercicio(nome="Desenvolvimento com halteres", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=2),
    Exercicio(nome="Desenvolvimento Arnold", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=2),
    Exercicio(nome="Elevação frontal com halteres", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=2),
    Exercicio(nome="Desenvolvimento com barra", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=3),
    Exercicio(nome="Remada alta", grupoMuscular=GrupoMuscularEnum.OMBROS, impacto_articular=3),

    Exercicio(nome="Rosca no cabo", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=1),
    Exercicio(nome="Rosca Scott na máquina", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=1),
    Exercicio(nome="Rosca Scott barra EZ", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=1),
    Exercicio(nome="Rosca concentrada", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=1),
    Exercicio(nome="Rosca alternada", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=2),
    Exercicio(nome="Rosca inclinada", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=2),
    Exercicio(nome="Rosca martelo", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=2),
    Exercicio(nome="Rosca direta barra EZ", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=2),
    Exercicio(nome="Rosca direta barra reta", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=3),
    Exercicio(nome="Rosca inversa barra", grupoMuscular=GrupoMuscularEnum.BICEPS, impacto_articular=3),

    Exercicio(nome="Tríceps corda", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=1),
    Exercicio(nome="Tríceps barra no pulley", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=1),
    Exercicio(nome="Extensão unilateral no cabo", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=1),
    Exercicio(nome="Máquina de tríceps", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=1),
    Exercicio(nome="Kickback", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=1),
    Exercicio(nome="Tríceps francês com halter", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=2),
    Exercicio(nome="Extensão acima da cabeça no cabo", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=2),
    Exercicio(nome="Tríceps testa barra EZ", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=2),
    Exercicio(nome="Supino fechado", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=3),
    Exercicio(nome="Paralelas com peso", grupoMuscular=GrupoMuscularEnum.TRICEPS, impacto_articular=3),

    Exercicio(nome="Crunch na máquina", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=1),
    Exercicio(nome="Abdominal no cabo", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=1),
    Exercicio(nome="Pallof Press", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=1),
    Exercicio(nome="Wood Chop no cabo", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=1),
    Exercicio(nome="Máquina abdominal", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=1),
    Exercicio(nome="Ab Wheel", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=2),
    Exercicio(nome="Hanging Leg Raise", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=2),
    Exercicio(nome="Roman Chair Sit-up", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=2),
    Exercicio(nome="Dragon Flag", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=3),
    Exercicio(nome="Toes to Bar", grupoMuscular=GrupoMuscularEnum.CORE, impacto_articular=3),
]